(function(a,v,r){function f(a,b){a.super_=b;e.prototype=b.prototype;a.prototype=new e;a.prototype.constructor=a}function e(){}function l(a,b){for(var q in b)b.hasOwnProperty(q)&&(a[q]=b[q]);return a}function n(a,b){return(b=b||r)&&b.getElementById&&b.getElementById(a)}function y(a,b){var q=b?a.substr?n(a):a:r;return q?q.getElementsByTagName(b||a):[]}function z(a,b){return~(" "+a.className+" ").indexOf(" "+b+" ")}function x(a,b){z(a,b)&&(a.className=(" "+a.className+" ").replace(" "+b+" "," ").slice(1,
-1),x(a,b))}function w(a){var q=a.offsetTop,c=a.offsetLeft,d,e=b.curCSS,f="static"!=e(a,"position");q||(q=(parseFloat(e(a,"marginTop"))||0)+(f?parseFloat(e(a,"top"))||0:0));c||(c=(parseFloat(e(a,"marginLeft"))||0)+(f?parseFloat(e(a,"left"))||0:0));f&&a.getBoundingClientRect&&(d=b.offset(a,!0));!q&&d&&(q=d.top);!c&&d&&(c=d.left);return{top:q,left:c}}function I(a){var b={relativeX:a[B[0]],relativeY:a[B[1]]};if(null==a.pageX&&null!=a.clientX){var q=r.documentElement,c=r.body;b.pageX=a.clientX+(q&&q.scrollLeft||
c.scrollLeft||0);b.pageY=a.clientY+(q&&q.scrollTop||c.scrollTop||0)}else b.pageX=a.pageX,b.pageY=a.pageY;return b}function P(a,c){if(!(a=a.parentNode))return!1;var q=a.ownerDocument,d=q.body,e=b.curCSS,f;c&&(c+=1);if(v.$sf)return!0;if(b.isIE&&(8>q.documentMode||"BackCompat"==q.compatMode))return!1;for(;a&&a!=d;){if("hidden"==e(a,"overflow"))return!1;if("fixed"==e(a,"position"))break;else if(c&&(f=parseInt(e(a,"z-index"),10))&&f<c)return!1;a=a.parentNode}return!0}function u(){for(var a=0,b=[];a<W.length;a++)"complete"!=
W[a].document.readyState&&b.push(W[a]);if(!(W=b).length||3E4<(new Date).getTime()-F){E=clearInterval(E);for(a=0;a<M.length;a++)M[a]();M=[];W=[]}}function k(a,b){var q=Math.max(a.x,b.x),c=Math.max(a.y,b.y),d=Math.min(a.x+a.width,b.x+b.width)-q;a=Math.min(a.y+a.height,b.y+b.height)-c;return 0<d&&0<a?{x:q,y:c,width:d,height:a}:{x:0,y:0,width:0,height:0}}function N(a,c,d,e){var q=function(a){e&&e.apply(a,arguments)},f=y(d,"head");f=f&&f[0];if(!f)try{throw Error("Can't find head tag.");}catch(ca){q(ca)}var Z=
c.src||c.href,g=Z.replace(/[^\da-z_-]/gi,"_"),h=d.adformId||b.gid("doc_"),ba=h+"|"+g,k=Y[ba];g=b.byTag(d,a);var V=0,n=g.length;d.adformId=d.adformId||h;if(k)k.loaded?q():k.callbacks.push(q);else{for(;V<n;++V)if(g[V].src==Z||g[V].href==Z){q();return}Y[ba]=k={doc:d,src:Z,callbacks:[q]};var m=d.createElement(a);l(m,c);if(e){var p=function(a){m.onload=m.onreadystatechange=m.onerror=null;a?Y[ba]=null:k.loaded=1;var b=k.callbacks;V=0;for(n=b.length;V<n;++V)b[V](a)};m.onload=function(){p()};m.onreadystatechange=
function(){"complete"==m.readyState&&p()};m.onerror=function(){try{throw Error("Failed to load script: "+Z);}catch(ca){p(ca)}}}setTimeout(function(){f.insertBefore(m,f.firstChild)},400)}}a.Log||(a.Log={});a.Log.pushMessage||(a.Log.pushMessage=function(){});a.Log.sendMessage||(a.Log.sendMessage=function(){});a.RMB=a.RMB||{};var d=a.RMB,b=d.lib||(d.lib={});a.lib||(a.lib=b);b.inherit=f;b.define=function(a,b,c){c&&f(a,b);c(a,a.prototype)};b.gid=function(a){var b=+new Date;return(a||"")+(b+b*~~(1E4*Math.random())).toString(36)};
b.byId=n;b.byTag=y;b.bind=function(a,b){return function(){return b.apply(a,arguments)}};b.extend=l;b.isMouseLeave=function(a,b){if(!a||"mouseout"!=a.type)return!0;a=a.relatedTarget||a.toElement;for(var c,q=b.length;a;){for(c=0;c<q;c++)if(b[c]==a)return!1;a=a.parentNode}return!0};b.singleCall=function(a){function b(){e=!1;var a=q,b=c,f=d;c=q=d=null;a&&a.apply(b,f)}var c,q,d,e;return function(f,g){c=f;q=g;d=t.call(arguments,2);g&&!e?e=setTimeout(b,a):!g&&e&&(clearTimeout(e),e=!1)}};b.onload=function(a,
b){try{do{if(a[O])break;a[O]=!0;"complete"!=a.document.readyState&&(W.push(a),E||(F=(new Date).getTime(),E=setInterval(u,200)))}while(a!=a.parent&&(a=a.parent))}catch(ba){}E?M.push(b):setTimeout(b,0)};b.overlap=k;b.overlapElem=function(a,c){var d=b.offset(a),q=b.offset(c);return k({x:d.left,y:d.top,width:a.offsetWidth,height:a.offsetHeight},{x:q.left,y:q.top,width:c.offsetWidth,height:c.offsetHeight})};b.hasClass=z;b.addClass=function(a,b){z(a,b)||(a.className+=" "+b)};b.removeClass=x;b.loadScript=
function(a,b,c){N("script",{src:b,type:"text/javascript"},a,c)};b.loadCSS=function(a,b){N("link",{href:b,type:"text/css",rel:"stylesheet"},a)};b.navigator=v.navigator;b.isTMX=function(a){try{var b=a.document,c=b&&b.body;return c&&z(c,"tmx")}catch(V){}return!1};b.isolate=function(a,b){var c=a.__adform_isolate;if(!c){var d=a.document;c=y(d,"head")[0];d=d.createElement("script");d.type="text/javascript";d.text='function __adform_isolate(f){new Function("window","("+f+")(window)")(window)}';c.insertBefore(d,
c.firstChild);c.removeChild(d);c=a.__adform_isolate}c?c(b):(new Function("window","("+b+")(window)"))(a)};var t=Array.prototype.slice;b.addEvent=function(a,b,c){return a[C]?a[C](b,c,!1):a[h]?a[h]("on"+b,c):!1};b.removeEvent=function(a,b,c){return a[A]?a[A](b,c,!1):a[g]?a[g]("on"+b,c):!1};var C="addEventListener",A="removeEventListener",h="attachEvent",g="detachEvent",p=/([A-Z])/g,m=/^-?\d+(?:px)?$/i,S=/^-?\d/;a=r.defaultView;b.curCSS=a&&a.getComputedStyle?function(a,b){var c=a.ownerDocument.defaultView;
if(c&&(c=c.getComputedStyle(a,null)))return c.getPropertyValue(b.replace(p,"-$1").toLowerCase())||a.style[b]}:r.documentElement.currentStyle&&function(a,b){var c,d,e=a.currentStyle&&a.currentStyle[b];if(!m.test(e)&&S.test(e)){var f=(d=a.style).left;if(c=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;d.left="fontSize"===b?"1em":e||0;e=d.pixelLeft+"px";d.left=f;c&&(a.runtimeStyle.left=c)}return""===e?"auto":e};var R=function(){function a(){return a}var b=r.body,c=r.createElement("div");
var d=["position:absolute;top:0;left:0;margin:0;padding:0;border:0;width:1px;height:1px;"].pop();c.innerHTML='<div style="'+d+'visibility:hidden"><div style="'+d+'border:5px solid #000"><div style="margin:0"></div></div><div style="'+d+'"><div style="'+d+'position:fixed;top:20px;"></div></div><div style="'+d+'position:relative;border:5px solid #000;overflow:hidden"><div style="margin:0"></div></div><table style="'+d+'border:5px solid #000" cellpadding="0" cellspacing="0"><tr><td></td></tr></table></div>';
b.insertBefore(c=c.firstChild,b.firstChild);d=c.childNodes;a.dnab=5!==d[0].firstChild.offsetTop;a.sfp=20===d[1].firstChild.offsetTop;a.sbfonv=-5===d[2].firstChild.offsetTop;a.dabftac=5===y(c,"td").offsetTop;b.removeChild(c);b=c=d=null;return R=a},T=/^t(?:able|d|h)$/i;b.offsetFromWindow=function(a){var c=a&&a.ownerDocument;if(!c)return null;var d=c.documentElement;if("getBoundingClientRect"in d){try{var e=a.getBoundingClientRect();var f=d.getBoundingClientRect()}catch(fa){}if(!e)return{top:0,left:0};
if(0<f.left||0<f.top)e.top-=f.top,e.left-=f.left;return{top:e.top,left:e.left}}e=c.defaultView||c.parentWindow;f=c.body;if(a===c.body)return w(a);a=b.offset(a);c=e&&e.pageYOffset||d.scrollTop||f.scrollTop;d=e&&e.pageXOffset||d.scrollLeft||f.scrollLeft;a.top-=c;a.left-=d;return a};b.offset="getBoundingClientRect"in r.documentElement?function(a,b){var c=a&&a.ownerDocument;if(!c)return null;if(!b&&a===c.body)return w(a);try{var d=a.getBoundingClientRect()}catch(ea){}if(!d)return{top:0,left:0};a=c.body;
c=c.documentElement;return{top:d.top+(c.scrollTop||a.scrollTop)-(c.clientTop||a.clientTop||0),left:d.left+(c.scrollLeft||a.scrollLeft)-(c.clientLeft||a.clientLeft||0)}}:function(a){var b=a&&a.ownerDocument;if(!b)return null;if(a===b.body)return w(a);var c=a.offsetParent,d=b.documentElement,e=b.body;var f=(b=b.defaultView)?b.getComputedStyle(a,null):a.currentStyle;for(var g=a.offsetTop,h=a.offsetLeft,k=R();(a=a.parentNode)&&a!==e&&a!==d&&(!k.sfp||"fixed"!==f.position);)f=b?b.getComputedStyle(a,null):
a.currentStyle,g-=a.scrollTop,h-=a.scrollLeft,a===c&&(g+=a.offsetTop,h+=a.offsetLeft,!k.dnab||k.dabftac&&T.test(a.nodeName)||(g+=parseFloat(f.borderTopWidth)||0,h+=parseFloat(f.borderLeftWidth)||0),c=a.offsetParent),k.sbfonv&&"visible"!==f.overflow&&(g+=parseFloat(f.borderTopWidth)||0,h+=parseFloat(f.borderLeftWidth)||0);if("relative"===f.position||"static"===f.position)g+=e.offsetTop,h+=e.offsetLeft;k.sfp&&"fixed"===f.position&&(g+=Math.max(d.scrollTop,e.scrollTop),h+=Math.max(d.scrollLeft,e.scrollLeft));
return{top:g,left:h}};b.client=function(a){a=a.ownerDocument||a;var b=a.defaultView||a.parentWindow;var c=a.documentElement;var d=a.body;if(b.innerWidth){a=b.innerWidth;var e=b.innerHeight}else c?(a=c.clientWidth,e=c.clientHeight,a&&d.clientHeight==d.offsetHeight||(a=Math.min(a||123456789,d.clientWidth||123456789),e=Math.min(e||123456789,d.clientHeight||123456789))):(a=d.clientWidth,e=d.clientHeight);return{left:b&&b.pageXOffset||c&&c.scrollLeft||d&&d.scrollLeft||0,top:b&&b.pageYOffset||c&&c.scrollTop||
d&&d.scrollTop||0,width:a,height:e}};b.isArray=Array.isArray||function(a){return"[object Array]"==Object.prototype.toString.call(a)};var B=[["offsetX","offsetY"],["layerX","layerY"]];b.getMousePos=function(a){for(var c;c=B.shift();)if("undefined"!=typeof a[c[0]]){B=c;break}c||(B=["x","y"]);b.getMousePos=I;return I(a)};var J=r.createElement("div");b.html=function(a,b){b=!b&&J||b.createElement("div");b.innerHTML=a;return b.firstChild&&b.removeChild(b.firstChild)};a=b.navigator;var D=a.vendor;a=a.userAgent;
var U=/Apple Computer/i.test(D);d=/Google/i.test(D);var Q=b.isIPad=/iPad/i.test(a),G=b.isIPhone=/iPhone/i.test(a),H=b.isIOS=Q||G,K=b.isTouch="ontouchstart"in r.documentElement||"ontouchstart"in v;Q=b.isOrientation="orientation"in v;G=b.isAndroid=!H&&/Android/i.test(a);b.isAndroidApp=G&&!/^(?:Opera|Mozilla)/i.test(a);var L;b.isIOSF=H&&(L=/\sos\s(\d+)_\d+/i.exec(a))&&(L=4<L[1]>>0);var c=b.isMobile=/Mobile|Mobi|Tablet|Nokia/i.test(a)||K;L=b.isIE=/msie|Trident/i.test(a);K=b.isFF=/Firefox[\/.]+[^\s]/i.test(a);
b.isMACOS=/Mac OS X/i.test(a);(b.isWinPhone=L&&c&&/Phone/gi.test(a))&&(c=/Windows Phone (OS )?(\d+[\.\d]*)/i.exec(a))&&c[2]&&(b.winPhoneVer=parseFloat(c[2]));c=b.isOpera=/Opera/i.test(a);var X=b.isOperaMobile=/Opera\s(?!Mini)/i.test(a),aa=b.isOperaMini=/Opera\sMini/i.test(a);D=b.isOperaWebKit=/OPR/i.test(a)&&/Opera Software/i.test(D);H=b.isChrome=/(Chrome|CriOS)+\/[\d\.]+\s/i.test(a)&&(H?U:d);U=b.isSafari=!/Chrome|CriOS|Skyfire/i.test(a)&&/Safari+\/[\.\d]+$/i.test(a)&&U;d=b.isInternet=G&&!H&&Q&&/Safari\/[\.\d]+$/i.test(a)&&
d;b.isEdge=/Edge\/[\.\d]+$/i.test(a);b.isAfmaSDK=/afma-sdk/i.test(a);var da=L?"msie":K?"firefox":X?"operaMobile":aa?"operaMini":c?"opera":D?"operaWebKit":H?"chrome":U?"safari":d?"internet":!1;b.browser=function(){return da};b.isIE&&("Microsoft Internet Explorer"==b.navigator.appName&&/MSIE (\d+[\.\d]*)/i.exec(a)||/rv:(\d+[\.\d]*)/i.exec(a))&&(b.ieVersion=parseFloat(RegExp.$1));b.testPlace=b.isIE&&8>b.ieVersion?function(){return!1}:P;b.isSafari&&(a=/Version.([\d.]+)/.exec(a),b.safariVersion=parseFloat(a&&
a[1]));var W=[],M=[],O="__adform_onload",E,F,Y={}})(Adform=window.Adform||{},window,document);
(function(a){function v(){}a.RMB=a.RMB||{};a.RMB.EventEmitter=v;var r=Array.prototype.slice;a=v.prototype;a.emit=function(a){var e=this._events,f=!1,n=arguments;if(e&&(e=e[a]))if("function"==typeof e){switch(n.length){case 1:e.call(this);break;case 2:e.call(this,n[1]);break;case 3:e.call(this,n[1],n[2]);break;case 4:e.call(this,n[1],n[2],n[3]);break;default:e.apply(this,r.call(n,1))}f=!0}else if(e.length){n=r.call(n,1);e=e.slice();f=0;for(var v=e.length;f<v;f++)e[f].apply(this,n);f=!0}else delete this._events[a];
return f};a.on=function(a,e){this._events||(this._events={});this.emit("newListener",a,e);var f=this._events;f[a]?"function"==typeof f[a]?f[a]=[f[a],e]:f[a].push(e):f[a]=e;return this};a.once=function(a,e){var f=e._once;f?f._times++:(f=e._once=function(){this.off(a,f);1>--f._times&&delete e._once;return e.apply(this,arguments)},f._times=1);return this.on(a,f)};a.off=function(a,e){if(!this._events||!this._events[a])return this;var f=this._events,n=f[a];if(n==e)return delete f[a],this;e&&e._once&&this.off(e._once);
if("function"==typeof n)return this;if(2>n.length&&n[0]==e)return delete f[a],this;for(var r=0,v=n.length,x=[];r<v;r++)n[r]!=e&&x.push(n[r]);x.length!=v&&(x.length?f[a]=x:delete f[a]);return this};a.clear=function(a){a?this._events&&this._events[a]&&delete this._events[a]:delete this._events;return this};a.list=function(a){this._events||(this._events={});var e=this._events;e[a]?"function"==typeof e[a]&&(e[a]=[e[a]]):e[a]=[];return e[a]}})(Adform=window.Adform||{});
/*
 mustache.js - Logic-less {{mustache}} templates with JavaScript
 http://github.com/janl/mustache.js
*/
(function(a,v,r){function f(a){return parseInt(a,10)?a:0}function e(){}function l(a,e,f){function w(){d=!1;var b=l;l=[];f(function(a){for(var d=0;d<b.length;d++)if(a)b[d][1](a);else k(b[d][0],b[d][1])})}function k(b,t){var k=!1;e(b,function(){k=!0;t.apply(this,arguments)});k||(l.push([b,t]),d||(d=setTimeout(w,a)))}var l=[],d=!1;return k}function n(a,e,f){var u=a["@id"]||0;var k=a["@pdata"]||"";var l={$id:u,$name:a["@name"]||"default",$link:f.replace(/adfibeg=\d+/,k?"pdata="+k:"adfibeg="+u),$pdata:k};
if(a.TextVars)for(f=0,u=a.TextVars.TextVar,k=u.length,x.isArray(u)||(u=[u],k=1);f<k;f++){var d=u[f];var b=d["@name"];d=d["@value"];l[b]=d;"product_deeplink"==b&&(l.$link+=";cpdir="+encodeURIComponent(d))}if(a.Graphics)for(f=0,u=a.Graphics.Graphic,k=u.length,x.isArray(u)||(u=[u],k=1);f<k;f++)d=u[f],l[d["@name"]]=e+d["@value"]+"?assetID="+d["@assetID"]+"&av="+d["@av"];return l}function y(a,f,e){var l=a.root;a={};if(l.TextVars||l.Graphics)a[0]=a[""]=n(l,f,e);if(l.Groups){var k=0,w=l.Groups.Group,d;x.isArray(w)||
(w=[w]);for(d=w.length;k<d;k++){var b=n(w[k],f,e);a[b.$id]=b}}f=l.GroupIds?l.GroupIds.split(","):[];return{ids:f,items:a,total:f.length}}var z=a.AdMessage||(a.AdMessage={}),x=a.lib;z.build=function(a){function n(){var c=G?G.length:0;return{total:c,totalPages:Math.ceil(c/d),pageSize:d,ids:G||[],limit:w}}function r(c,a,b){z.load(S[c]+"&"+a,function(c,a){c?b(c):b(null,y(a,p,g))})}function u(c){if(c)for(var a in c)c.hasOwnProperty(a)&&(Q[a]=c[a])}var k=v.dhtml&&dhtml.getVar()||{},w=f(a.limit)||100,d=
f(a.pageSize)||1,b=f(a.cid||k.cid),t=f(a.tid||k.tid),C=f(a.tv||k.tv)||+new Date,A=f(a.bn||k.bn),h=a.gid||k.gid||0,g=a.clickTAG||"",p=(a.statics||a.domain||k.staticDomain||k.domain).replace(/\/+$/,""),m=(a.domain||k.domain).replace(/(\w+:\/\/[^\/]+\/).*/,"$1"),S={adMessage:m+"Serving/AdMessage/?",recommendations:m+"dco/recommendations/?",products:m+"dco/products/?"};b="aid="+b+"&tid="+t+"&tv="+C;t=f(a.icid||k.icid)||"0";C=k.unloadID||"0";m=k.geo||"0;0;0";var R=a.eshopId||k.trackingSetupId||"0",T=k.ADFbanID||
"0",B=f(a.rotseqno||k.rotseqno),J=a.smid||k.smid,D=a.dcoEngineId||k.dcoEngineId;a=k.ccpa;k.versionListId&&(b+="&versionListId="+k.versionListId);k.versionId&&(b+="&versionId="+k.versionId);t&&(b+="&icid="+t);R&&(b+="&eid="+R);B&&(b+="&rotseqno="+B);J&&(b+="&smid="+J);D&&(b+="&dco="+D);T&&(b+="&bnrid="+T);C&&(b+="&intid="+C);m&&(b+="&geo="+m.split(";").join(","));for(var U in S)S[U]+=b;S.recommendations+=a?"&ccpa="+a:"";var Q={},G,H=0,K=l(100,function(c,a){c*=d;var b=c+2*d;H=Math.max(H,b);if(G)if(c=
G.slice(c,b),c.length)a(null,c,n());else try{throw Error("AdMessage page not found.");}catch(M){a(M)}},function(c){r(D?"recommendations":"adMessage","bn="+A+"&gcnt="+w+"&pgsz="+Math.min(H,w),function(a,b){if(a)c(a);else if(u(b.items),(G=b.ids)&&G.length)c();else try{throw Error("AdMessage template doesn't contain groups.");}catch(M){c(M)}});H=0}),L={},c=[],X=l(100,function(a,b){for(var h=a._test||0,g=[],d=0,p=a.length,t,m;d<p;d++)(m=Q[t=a[d]])?g.push(m):L[t]||(L[t]=!0,c.push(t));a._test=++h;if(g.length==
a.length)b(null,g,n());else if(4<h)try{throw Error("AdMessage group"+((1<a.length?'s "':' "')+a.join(", "))+'" not found.');}catch(q){b(q)}},function(a){c.length?r(D?"products":"adMessage","bn="+A+"&gid="+c.join(","),function(c,b){L={};c?a(c):(u(b.items),a())}):setTimeout(function(){a()},100);c=[]});k.dynamicAdContent&&u(y(k.dynamicAdContent,p,g).items);return{setProperties:function(c){var a=c.pageSize>>0||d;c=c.limit>>0||w;0<c&&(w=c);0<a&&(d=Math.min(a,w))},getProperties:n,getPage:function(c,a){K((c>>
0)-1,function(c,b){c?a(c):(X(b.slice(0,d),a),X(b.slice(d),e))})},getItems:function(c,a){X(x.isArray(c)?c:[c],a)},getDefault:function(c){X([h],function(a,b,h){c(a,b&&b[0],h)})}}};z.load=function(a,f){var l=x.gid("adform_com_"),e=r.createElement("script"),k=function(){d();try{throw Error("AdMessage load error.");}catch(b){f(b)}},n=function(a){d();f(null,a)},d=function(){e.parentNode.removeChild(e);v[l]=e.onerror=e.onload=k=n=d=e=null};e.type="text/javascript";e.src=a+"&format=json&callback="+encodeURIComponent(l);
e.onload=e.onerror=function(){setTimeout(k,1E3)};v[l]=n;a=x.byTag(r,"script")[0];a.parentNode.insertBefore(e,a)}})(Adform=window.Adform||{},window,document);
(function(a,v,r,f){function e(){}function l(a){for(var b=k.length;0<b--;)if(k[b][0]==a)return k[b][1]}function n(a,e,f){function h(c){if(c&&R)b(R,"touchstart",I);else if(!R)try{(R=a.defaultView.frameElement)&&d(R,"touchstart",I)}catch(X){}}var g=l(a),p,m;g?p=g._:k.push([a,g={_:p=new u,_destroy:function(){p.clear();delete this._;delete this._destroy;for(var c in this)if("function"==typeof this[c])this[c]();for(c=k.length;0<c--;)if(k[c][0]==a){k.splice(c,1);break}}}]);var t,R,C,n,A,r,w,v;P.isIOS&&a.defaultView.frameElement&&
{click:1,mousedown:1,mouseup:1}[e]&&d(f,e,I);if(!g[e])switch(e){case "swipe":var G=function(a){if(t=x(p,a.target,"swipe")[0])a.preventDefault(),(a=a&&a.targetTouches)&&(a=a[0])&&(C=a.pageX,A=a.pageY,w=(new Date).getTime())};var H=function(a){var b=a&&a.targetTouches;t&&(a.preventDefault(),b&&(b=b[0])&&w&&(n=b.pageX,r=b.pageY,v=(new Date).getTime(),.2<Math.sqrt(Math.pow(n-C,2)+Math.pow(r-A,2))/(v-w)&&(a=A-r,b={type:"swipe"},b.directionX=0<C-n?"left":"right",b.directionY=0<a?"up":"down",b.target=t[1],
w=0,z(p,t[1],b))))};d(a,"touchstart",G);d(a,"touchend",H);d(a,"touchmove",H);h();g[e]=function(){b(a,"touchstart",G);b(a,"touchend",H);b(a,"touchmove",H);h(!0)};break;case "hover":if(a.addEventListener){var K=function(a){a=a.target;m!=a&&y(p,m,m=a)};var L=function(a){a=a.relatedTarget;m!=a&&y(p,m,m=a)}}else K=function(b){b=(a.defaultView||a.parentWindow).event.srcElement;m!=b&&y(p,m,m=b)},L=function(b){b=(a.defaultView||a.parentWindow).event.toElement;m!=b&&y(p,m,m=b)};d(a,"mouseover",K);d(a,"mouseout",
L);d(a,"mousemove",K);g[e]=function(){b(a,"mouseover",K);b(a,"mouseout",L);b(a,"mousemove",K);m=null};break;case "click":case "mousedown":case "mouseup":case "touchstart":case "touchmove":case "touchend":K=a.addEventListener?function(a){z(p,a.target,a)}:function(b){b=(a.defaultView||a.parentWindow).event;z(p,b.srcElement,b)},d(a,e,K),g[e]=function(){b(a,e,K)}}return!!g[e]}function y(a,b,d){d=x(a,d,"hover");b=x(a,b,"hover");for(var h=d.length,g=h,e=b.length,m=e-h;0<g--&&d[g][1]==(b[m+g]&&b[m+g][1]););
d.length=h=g+1;b.length=e=m+g+1;var f,l=a._events;if(l){for(m=g=-1;++m<e;)l[f=b[m][0]]&&a.emit(f,b[m][1],"hoverout");for(;++g<h;)l[f=d[g][0]]&&a.emit(f,d[g][1],"hoverin")}}function z(a,b,d,h){h=h||d;b=x(a,b,d.type);d=b.length;for(var g=0,e;e=b[g],g++<d;)a.emit(e[0],e[1],h)}function x(a,b,d){a=a._events;var h,g,e,f=[];if(a)for(;b&&"undefined"!=(e=typeof(g=b.className));)"string"==e&&~g.indexOf("adform-dom-")&&a[h=w(b)+":"+d]&&(f[f.length]=[h,b]),b=b.parentNode;return f}function w(a){a=a.className;
return~a.indexOf("adform-dom-")?a.match(N)[1]:P.gid()}function I(){}a.RMB=a.RMB||{};a=a.RMB;a.DOMEvents=e;var P=a.lib,u=a.EventEmitter,k=[],N=/adform-dom-(\S+)/,d=P.addEvent,b=P.removeEvent;e.has=function(a){return!!{hover:1,mousedown:1,mouseup:1,click:1,swipe:1,touchstart:1,touchmove:1,touchend:1}[a]};e.on=function(a,b,d){var h=a.ownerDocument;if(n(h,b,a)){var e=w(a);P.addClass(a,"adform-dom-"+e);l(h)._.on(e+":"+b,d);return!0}return!1};e.off=function(a,b,d){l(a.ownerDocument)._.off(w(a)+":"+b,d)};
e.destroy=function(a){l(a)._destroy()}})(Adform=window.Adform||{},window,document);
var Mustache="undefined"!==typeof module&&module.exports||{};
(function(a){function v(a){return String(a).replace(/&(?!\w+;)|[<>"']/g,function(a){return C[a]||a})}function r(a,b,d,e){e=e||"<template>";var h=b.split("\n"),g=Math.max(d-3,0);h=h.slice(g,Math.min(h.length,d+3));for(var f,l=0,m=h.length;l<m;++l)f=l+g+1,h[l]=(f===d?" >> ":"    ")+h[l];a.template=b;a.line=d;a.file=e;a.message=[e+":"+d,h.join("\n"),"",a.message].join("\n");return a}function f(a,b,d){if("."===a)return b[b.length-1];a=a.split(".");for(var h=a.length-1,e=a[h],f,g,l=b.length,p,k;l;){k=
b.slice(0);g=b[--l];for(p=0;p<h;){g=g[a[p++]];if(null==g)break;k.push(g)}if(g&&"object"===typeof g&&e in g){f=g[e];break}}"function"===typeof f&&(f=f.call(k[k.length-1]));return null==f?d:f}function e(a,b,d,e){var h="";a=f(a,b);if(e){if(null==a||!1===a||u(a)&&0===a.length)h+=d()}else if(u(a))k(a,function(a){b.push(a);h+=d();b.pop()});else if("object"===typeof a)b.push(a),h+=d(),b.pop();else if("function"===typeof a){var g=b[b.length-1];h+=a.call(g,d(),function(a){return z(a,g)})||""}else a&&(h+=d());
return h}function l(b,e){e=e||{};for(var h=e.tags||a.tags,f=h[0],l=h[h.length-1],g=['var buffer = "";',"\nvar line = 1;","\ntry {",'\nbuffer += "'],k=[],n=!1,t=!1,w=function(){if(!n||t||e.space)k=[];else for(;k.length;)g.splice(k.pop(),1);t=n=!1},u=[],v,y,x,z=function(a){h=d(a).split(/\s+/);y=h[0];x=h[h.length-1]},A=function(a){g.push('";',v,'\nvar partial = partials["'+d(a)+'"];',"\nif (partial) {","\n  buffer += render(partial,stack[stack.length - 1],partials);","\n}",'\nbuffer += "')},c=function(a,
c){a=d(a);if(""===a)throw r(Error("Section name may not be empty"),b,M,e.file);u.push({name:a,inverted:c});g.push('";',v,'\nvar name = "'+a+'";',"\nvar callback = (function () {","\n  return function () {",'\n    var buffer = "";','\nbuffer += "')},C=function(a){c(a,!0)},I=function(a){a=d(a);var q=0!=u.length&&u[u.length-1].name;if(!q||a!=q)throw r(Error('Section named "'+a+'" was never opened'),b,M,e.file);a=u.pop();g.push('";',"\n    return buffer;","\n  };","\n})();");a.inverted?g.push("\nbuffer += renderSection(name,stack,callback,true);"):
g.push("\nbuffer += renderSection(name,stack,callback);");g.push('\nbuffer += "')},P=function(a){g.push('";',v,'\nbuffer += lookup("'+d(a)+'",stack,"");','\nbuffer += "')},W=function(a){g.push('";',v,'\nbuffer += escapeHTML(lookup("'+d(a)+'",stack,""));','\nbuffer += "')},M=1,O,E,F=0,Y=b.length;F<Y;++F)if(b.slice(F,F+f.length)===f){F+=f.length;O=b.substr(F,1);v="\nline = "+M+";";y=f;x=l;n=!0;switch(O){case "!":F++;E=null;break;case "=":F++;l="="+l;E=z;break;case ">":F++;E=A;break;case "#":F++;E=c;
break;case "^":F++;E=C;break;case "/":F++;E=I;break;case "{":l="}"+l;case "&":F++;t=!0;E=P;break;default:t=!0,E=W}O=b.indexOf(l,F);if(-1===O)throw r(Error('Tag "'+f+'" was not closed properly'),b,M,e.file);f=b.substring(F,O);E&&E(f);for(E=0;~(E=f.indexOf("\n",E));)M++,E++;F=O+l.length-1;f=y;l=x}else switch(O=b.substr(F,1),O){case '"':case "\\":t=!0;g.push("\\"+O);break;case "\r":break;case "\n":k.push(g.length);g.push("\\n");w();M++;break;default:N.test(O)?k.push(g.length):t=!0,g.push(O)}if(0!=u.length)throw r(Error('Section "'+
u[u.length-1].name+'" was not closed properly'),b,M,e.file);w();g.push('";',"\nreturn buffer;","\n} catch (e) { throw {error: e, line: line}; }");l=g.join("").replace(/buffer \+= "";\n/g,"");e.debug&&("undefined"!=typeof console&&console.log?console.log(l):"function"===typeof print&&print(l));return l}function n(a,b){var d=l(a,b),h=new Function("view,partials,stack,lookup,escapeHTML,renderSection,render",d);return function(d,l){l=l||{};var g=[d];try{return h(d,l,g,f,v,e,z)}catch(B){throw r(B.error,
a,B.line,b.file);}}}function y(a,b){b=b||{};return!1!==b.cache?(A[a]||(A[a]=n(a,b)),A[a]):n(a,b)}function z(a,b,d){return y(a)(b,d)}a.name="mustache.js";a.version="0.5.0-dev";a.tags=["{{","}}"];a.parse=l;a.compile=y;a.render=z;a.clearCache=function(){A={}};a.to_html=function(a,b,d,e){a=z(a,b,d);if("function"===typeof e)e(a);else return a};var x=Object.prototype.toString,w=Array.isArray,I=Array.prototype.forEach,P=String.prototype.trim;var u=w?w:function(a){return"[object Array]"===x.call(a)};var k=
I?function(a,b,d){return I.call(a,b,d)}:function(a,b,d){for(var e=0,f=a.length;e<f;++e)b.call(d,a[e],e,a)};var N=/^\s*$/;if(P)var d=function(a){return null==a?"":P.call(a)};else{if(N.test("\u00a0")){var b=/^\s+/;var t=/\s+$/}else b=/^[\s\xA0]+/,t=/[\s\xA0]+$/;d=function(a){return null==a?"":String(a).replace(b,"").replace(t,"")}}var C={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"},A={}})(Mustache);
(function(a,v,r){function f(){if(v.Ready)for(var c=0;c<Ready.length;c++)n(Ready[c]);v.Ready={push:n}}function e(c,a){var b=p,h="undefined"==typeof p[c],d="undefined"==typeof g[c];if(c)if(h&&d){b=a;try{var t=_Adform.Log.pushMessage;/^c.*tag/i.test(c)?t("flashvars_clicktag",[c,"bn:",p.bn].join(" "),1):"bn"==c?t("flashvars_bn","bn: "+p.bn,1):~"autoPlay loopVideo soundOn inview autoPause playOnExpand".indexOf(c)?t("flashvars_video",[c,"bn:",p.bn].join(" "),0,"info"):~"dcoEngineId dynamicAdContent gid tv tid autoScroll".indexOf(c)?
t("flashvars_dco",[c,"bn:",p.bn].join(" "),0,"info"):t("flashvars_other",[c,"bn:",p.bn].join(" "),0,"info")}catch(O){}}else b=h?g[c]:p[c];return b}function l(c){c=parseInt(c,10);var a=e("videoSources");if(a)for(var b=a.length,h,g=0;g<b;g++)if(h=a[g],h.id==c)return h.file}function n(c){c.call(v);L||(clearTimeout(K),K=setTimeout(function(){L=!0;r.close()},1E3))}function y(c,a){"function"==typeof a&&(c=a);try{throw Error("AdMessage template id is missing");}catch(aa){if("function"==typeof c)c(aa);else throw aa;
}}function z(c,a,b,d){var t=v._Adform&&_Adform.Events;if(t&&t.sendEvent){if(c in B)a=B[c];else if(isNaN(c=parseInt(c,10))||1>c||20<c&&200>c||250<c)throw Error("Custom event id="+c+" must be between 1-20 for engaging and 200-250 for non-engaging events");if(!a)throw Error("Event name is missing");var p=[""];if(b)for(var m in b){var e=m.slice(0,2),f=parseInt(m.slice(2),10);"bv"==e&&0<f&&256>f&&p.push(m+"="+encodeURIComponent(b[m]))}d&&p.push(d);t.sendEvent(g.xId,c,h.assetId,a,p.join("&"),"Standard HTML");
return!0}return!1}function x(c,a){u[c]||(u[c]=Mustache.compile(w(c).text));if(a){if(N.length!=t){for(var b=0;b<N.length;b++)"text/mustache"==N[b].type&&x(N[b].id);t=N.length}return u[c](a,u)}return u[c]}function w(a){return r.getElementById(a)}for(var I=a.RMB.lib,P=I.isArray,u={},k,N=r.getElementsByTagName("script"),d=0,b;d<N.length;d++)if(b=(N[d].src||"").match(/(^.*)rmb\/Adform\.DHTML\.js/)){k=b[1]+"components/";break}var t=0,C=a.RMB.EventEmitter;b=a.RMB.DOMEvents;var A=v._AdformContent||{},h=A.data||
{},g=A.options||{},p=h.flashvars,m=a.tagData;if(!p&&(p={},m)){d=m.customVariables;m=m.clickUrls;if(d)for(var S in d)p[S]=d[S];for(var R in m)p[R]=m[R]}var T=new C;a.on=function(){T.on.apply(T,arguments)};a.off=function(){T.off.apply(T,arguments)};a.emit=function(){T.emit.apply(T,arguments)};var B={151:"Previous Product Button Press",150:"Next Product Button Press",143:"Banner Collapse",22:"Other Expands",21:"First Expand",168:"Auto Expands",161:"Hide Expanding Banner Button Press",23:"Close Button Press",
25:"Video Play Start",26:"Played 25% Of Video",27:"Played 50% Of Video",28:"Played 75% Of Video",29:"Video Playback Complete",30:"Play Button Press",31:"Pause Button Press",32:"Stop Button Press",33:"Sound On Button Press",34:"Sound Off Button Press",35:"Full Screen On Button Press",36:"Full Screen Off Button Press",38:"Rewind Button Press","":""};a.EVENT_FIRST_EXPAND=[21,B[21]];a.EVENT_OTHER_EXPAND=[22,B[22]];a.EVENT_CLOSE=[23,B[23]];a.EVENT_COLLAPSE=[143,B[143]];for(d=1;251>d;d++)if(21>d||199<d)a["EVENT_CUSTOM_"+
d]=[d,"Custom Event "+d];a.sendRequest=function(a){(new Image).src=a};a.sendEvent=function(a){var c,b,h=arguments;if(c=P(a)&&1<a.length){for(c=1;c<h.length&&256>c;c++)(b=b||{})["bv"+c]=h[c];c=z(a[0],a[1],b)}return c};a.getClickURL=function(a,b){return e(a||h.defaultClickTAG||"clickTAG",b)||null};a.getLocation=function(){var a=v._Adform&&_Adform.locationInfo||null;a&&(a.lng=a.Longitude,a.lat=a.Latitude);return a};a.getAsset=function(a){return l(a)||null};a.getVar=function(a){return a&&void 0!==p[a]?
p[a]:null};var J=v.dhtml={PREVIOUS_BUTTON_PRESS:151,NEXT_BUTTON_PRESS:150,CLOSE_BUTTON_PRESS:23,COLLAPSE_EVENT:143,EXPAND_EVENT:22,FIRST_EXPAND_EVENT:21,AUTO_EXPAND_EVENT:168,SUPER_CLOSE_EVENT:161,VIDEO_PROG_0:25,VIDEO_PROG_25:26,VIDEO_PROG_50:27,VIDEO_PROG_75:28,VIDEO_PROG_100:29,PLAY_BUTTON_PRESS:30,PAUSE_BUTTON_PRESS:31,STOP_BUTTON_PRESS:32,SOUND_ON_BUTTON_PRESS:33,SOUND_OFF_BUTTON_PRESS:34,FULL_SCREEN_ON_BUTTON_PRESS:35,FULL_SCREEN_OFF_BUTTON_PRESS:36,REWIND_BUTTON_PRESS:38,byId:w,hasClass:I.hasClass,
addClass:I.addClass,removeClass:I.removeClass,mustache:x,sendEvent:function(a,b,h){J.sharedEvents.emit(a+"",{id:a,name:b||B[a],vars:h});if(!(D&&D.callDHTMLEvent&&D.callDHTMLEvent.call(D,a)))return a in B&&(h=null),z(a,b,h)},$sendEvent:z,appendEvents:function(a){for(var c in a)B.hasOwnProperty(c)||(B[c]=a[c]);return B},getVar:e,getAsset:l,width:h.width,height:h.height,collapsedWidth:g.colWidth,collapsedHeight:g.colHeight,external:A.external||{},inscreen:new C,sharedEvents:A.sharedEvents||new C,scriptsBase:g.scriptsBase||
k+"../",getState:function(){return A.state?A.state():"visible"},on:b.on,off:b.off,connect:function(a){var c=v._Adform&&_Adform.ADFUtilInstance;a=a||p.bn||"x";c=c?c.getRotSeed():{};c.localConnections||(c.localConnections={});var b=c.localConnections[a];if(!b){b=new C;var h=[];b.expect=function(a,c){if(h.length>=a)c();else b.once("expect:"+a,c);return b};b.join=function(a){h.push(a);b.emit("member",a);b.emit("expect:"+h.length);return b};b.members=h;c.localConnections[a]=b}return b}};try{var D=parent.parent.getVPAIDAd&&
parent.parent.getVPAIDAd()}catch(c){}if(D&&D.callDHTMLEvent){J.vpaid=D;var U=J.external.close;J.external.close=function(){D.callDHTMLEvent.call(D,23);return U.apply(this,arguments)}}J.sharedEvents.on("newListener",function(a){"pageLoadComplete"==a&&setTimeout(function(){J.external.initPoliteMode()},0)});J.adMessage=p.tid?a.AdMessage.build({limit:100,pageSize:5}):{setProperties:y,getProperties:y,getPage:y,getItems:y,getDefault:y};var Q=J.inscreen;J.external.initInScreen&&(J.sharedEvents.on("updateInScreen",
function(a){for(var c in a)Q.emit(c,Q[c]=a[c]);Q.emit("change")}),a.on("newListener",function(c){"visibilityData"===c&&(a.off("newListener",arguments.callee),Q.on("change",function(){a.emit("visibilityData",{isVisible:Q.visible,visibleArea:Q.percent})}))}),Q.once("newListener",function(){setTimeout(function(){J.external.initInScreen()},0)}));components=v.preloadQueue||v.components||[];var G=components.length;for(d=0;d<components.length;d++)r.write('<script src="'+(k+"Adform."+components[d]+".js?bv="+
(p.bv||Math.random()))+'">\x3c/script>');try{var H=r.defaultView.frameElement;H&&I.addEvent(H,"touchstart",function(){})}catch(c){}J.registerComponent=function(a){for(var c=0;c<components.length;c++)components[c]==a&&G--;G||f()};G||f();var K,L})(Adform=window.Adform,window,document);
